### ISSUE TITLE
Things to fix or confirm in platform port

### ISSUE THREAD

**Issue by amcgee** [dhis2/usage-analytics-app#137]
- [x] i18n behavior and namespace isolation
- [x] `styled-jsx` support (why do we have console warnings again?)
- [ ] Migrate data access to `app-runtime`

**Comment by varl** [comment]
> styled-jsx support (why do we have console warnings again?)

Is it because of `optimizeForSpeed` again?

**Comment by amcgee** [comment]
@varl it might be, I haven't confirmed but it looks familiar!

**Comment by amcgee** [comment]
We set `optimizeForSpeed: true` though, so not sure what's up...

**Comment by amcgee** [comment]
We should be able to close this when we upgrade `cli-app-scripts`

**Comment by amcgee** [comment]
Ping

**Comment by ismay** [comment]
I've updated all dependencies to latest. Not getting any console warnings so I think that the above can all be considered resolved. Let me know if it isn't!
