### ISSUE TITLE
Don't require compile-time baseUrl or singleton store

### ISSUE THREAD

**Issue by amcgee** [dhis2/usage-analytics-app#297]
This causes problems when trying to work with different backends for testing (using the built-in platform login dialog) but is non-trivial to change, since data is threaded through redux and assumes a static baseUrl and singleton store.

**Comment by amcgee** [comment]
Work-in-progress branch [here](https://github.com/dhis2/usage-analytics-app/tree/wip/dynamic-baseurl)

**Comment by ismay** [comment]
Saw this pop up in slack. I'm also very busy with the scheduler app, but just wanted to mention what I know of the history this part of the app. It has been a while, but I can see that before this app was unejected it relied on `import { get } from '@dhis2/ui/utils/api'` (top line [here](https://github.com/dhis2/usage-analytics-app/pull/41/files?file-filters%5B%5D=.js&hide-deleted-files=true#diff-284817f1b6aad47c0ac6d61bd72f474c)).

That was replaced with the code that uses the env var, `src/api/get.js` ([here](https://github.com/dhis2/usage-analytics-app/pull/41/files?file-filters%5B%5D=.js&hide-deleted-files=true#diff-18b270b9e2eef14b15d866b083726c19)). I'll have to take more time to see why exactly (I assume it conflicted with the uneject). Could just be that I did something very naieve there. Just giving some quick context off the top of my head, not sure how valuable it is.

Maybe we could fix this by just addressing what's going on in api/get? As I said, just thinking out loud, need to take the time to read up on this to get some context.

**Comment by amcgee** [comment]
Thanks @ismay - yeah ideally we'd move to using the Data Engine for the two queries this app makes, but that's a bit more complicated since they're fetched from Redux (not impossible)

**Comment by amcgee** [comment]
Ping

**Comment by ismay** [comment]
Taking a look at this now

**Comment by ismay** [comment]
Resolved in https://github.com/dhis2/usage-analytics-app/pull/388
